"""
Django settings for ref_system project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here-change-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver','ref-ya68.onrender.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cerberus_user',
    'dashboard',
    'clubes',
    'derecho_admision',
    'operacionales',
    'redes_monitoring',
]

AUTH_USER_MODEL = 'cerberus_user.UsuarioCerberus'

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'dashboard.middleware.cerberus_token_middleware.CerberusTokenMiddleware',
    'dashboard.middleware.simple_auditoria_middleware.SimpleAuditoriaMiddleware',
]

ROOT_URLCONF = 'ref_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.user_profile',
            ],
        },
    },
]

WSGI_APPLICATION = 'ref_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

_DB_OPTIONS = {
    'charset': 'utf8mb4',
    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
}

DATABASES = {
    # Base de datos propia de Teseo (tablas de encuentros, incidentes, clubes, etc.)
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'teseo'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASS', ''),
        'HOST': os.environ.get('DB_HOST', '172.17.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': _DB_OPTIONS,
    },
    # Base de datos compartida de Cerberus (tabla usuarios — misma que usa el resto del sistema)
    'cerberus': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('CERBERUS_DB_NAME', 'usuarios'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASS', ''),
        'HOST': os.environ.get('DB_HOST', '172.17.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': _DB_OPTIONS,
    },
}

DATABASE_ROUTERS = ['ref_system.db_router.CerberusRouter']


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Autenticación
AUTHENTICATION_BACKENDS = [
    'dashboard.backends.CerberusBackend',
]

# Cerberus — servicio central de autenticación
CERBERUS_HOST = os.environ.get('CERBERUS_HOST', '172.17.0.1')
CERBERUS_PORT = os.environ.get('CERBERUS_PORT', '8004')
CERBERUS_API = f"http://{CERBERUS_HOST}:{CERBERUS_PORT}/cerberus/api/v1"
CERBERUS_API_KEY = os.environ.get('APP_API_KEY', '')
CERBERUS_JWT_SECRET = os.environ.get('CERBERUS_JWT_SECRET', '')

# Google Sheets Configuration
GOOGLE_SHEETS_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'credentials', 'google_sheets_credentials.json')

# RSS Feeds Configuration
RSS_FEED_URL = 'https://rss.app/feeds/_aUBB2qjedDT2RxdW.json'

# Tournament Google Sheets URLs
TOURNAMENT_SHEETS = {
    'LPF': {
        'encuentros': 'https://docs.google.com/spreadsheets/d/1-lYFhNHfLT7qnj6SxKqhUQ-fHYjdDAAT/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'ranking': 'https://docs.google.com/spreadsheets/d/1d1I_ljiyIP6UQ84dNxldg19yhUQ3iIFN/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'mapa': 'https://docs.google.com/spreadsheets/d/1d1I_ljiyIP6UQ84dNxldg19yhUQ3iIFN/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'clubes': 'https://docs.google.com/spreadsheets/d/18A90XIQ-0eXb9q_x8ZLYaavhQpmVWCHW/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'derecho_admision': 'https://docs.google.com/spreadsheets/d/1W9N9YmqRxlgSeCJ39WLbZ23L1ITDVTw6/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'operacionales': 'https://drive.google.com/file/d/1jrJ_iWNGbqLQ5GDYOq9mgz5KQTEJNOb_/view?usp=drive_link',
    },
    'ASCENSO': {
        'encuentros': 'https://docs.google.com/spreadsheets/d/1R_TYK51xLRJcyjiBAlHlrBtrKxHeehuo/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'clubes': 'https://docs.google.com/spreadsheets/d/1zOaXceeRJwja_0dsIMLjFHgl4Eux3bf7/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'derecho_admision': 'https://docs.google.com/spreadsheets/d/1PFgfR88ZCHFhleT_7bp8TN5p-QfIz7xZ/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'operacionales': 'https://drive.google.com/file/d/1HMLGAbXifwHSvpJgqOKlaQKYNBMI_pL_/view?usp=drive_link',
        'mapa': 'https://docs.google.com/spreadsheets/d/1sN8J7lUpf4eVIE_y3F9IWEC-_cRXXk8h/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
    },
    'COPA_ARGENTINA': {
        'encuentros': 'https://docs.google.com/spreadsheets/d/1TQYOmLbkdykEHz1iVw3AwKt8A3Wvn-gC/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'clubes': 'https://docs.google.com/spreadsheets/d/1hBkft64ISW7M6ESyBkveruUBqxrryT85/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'derecho_admision': 'https://docs.google.com/spreadsheets/d/1nf_oayZqj1c28ZEBeKvnZcXYEFYW8yhX/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'operacionales': 'https://drive.google.com/file/d/1WblcUlEOUASAzWFovkJ2tu4JFuLd58Xh/view?usp=drive_link',
    },
    'COPA_SUDAMERICANA': {
        'encuentros': 'https://docs.google.com/spreadsheets/d/1XnOvES7Rd3OVgvb37HYjQMtwJo1fRIhz/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'clubes': 'https://docs.google.com/spreadsheets/d/1T3MGWy0mVGxu6FqQAIw9zJqT7t_si1eD/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'derecho_admision': 'https://docs.google.com/spreadsheets/d/1UH8uoEImdYTXoGlLXiE_X5kVqcz62KPg/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'operacionales': 'https://drive.google.com/file/d/1gXZwLgLd_bA29egKnjCE3DNoAVdb_OVc/view?usp=drive_link',
    },
    'COPA_LIBERTADORES': {
        'encuentros': 'https://docs.google.com/spreadsheets/d/106MUaLytdvyvNiTiBiUZFHU0fqVMU1lW/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'clubes': 'https://docs.google.com/spreadsheets/d/1BodR1rkA3NaqtBpPMRdPQ1kcCSGz1_73/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'derecho_admision': 'https://docs.google.com/spreadsheets/d/1Dqbvm5XSbD0THhiVNa5zpgxTpV2qJ0V0/edit?usp=drive_link&ouid=105946427915639546375&rtpof=true&sd=true',
        'operacionales': 'https://drive.google.com/file/d/1whwfYBDMcJ6wN-Tdml9aX-ZxJ4mMMNkL/view?usp=drive_link',
    }
}

# Configuración de Google Sheets API
GOOGLE_SHEETS_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'credentials', 'just-coda-473000-f4-c4748e7930d6.json')