services:
  - type: web
    name: ref-system
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "ref-ya68.onrender.com,127.0.0.1,localhost"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
