# Generated by Django 4.2.7 on 2025-09-21 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionalVigente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torneo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('PLAN_SEGURIDAD', 'Plan de Seguridad'), ('PROTOCOLO', 'Protocolo'), ('MANUAL', 'Manual'), ('INSTRUCTIVO', 'Instructivo'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('archivo_pdf', models.FileField(upload_to='operacionales/pdfs/')),
                ('fecha_creacion', models.DateField()),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operacional Vigente',
                'verbose_name_plural': 'Operacionales Vigentes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
