# Generated by Django 4.2.7 on 2025-09-21 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_corto', models.CharField(max_length=20, unique=True)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='clubes/escudos/')),
                ('estadio', models.CharField(max_length=200)),
                ('direccion_estadio', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('fundacion', models.DateField(blank=True, null=True)),
                ('colores', models.CharField(blank=True, max_length=200, null=True)),
                ('presidente', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FaccionHinchas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('BARRA_BRAVA', 'Barra Brava'), ('HINCHADA', 'Hinchada'), ('GRUPO', 'Grupo'), ('BANDA', 'Banda'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('cantidad_estimada', models.IntegerField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facciones', to='clubes.club')),
            ],
            options={
                'verbose_name': 'Facción de Hinchadas',
                'verbose_name_plural': 'Facciones de Hinchadas',
                'unique_together': {('club', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='TerritorioHinchas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('coordenadas_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coordenadas_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('faccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territorios', to='clubes.faccionhinchas')),
            ],
            options={
                'verbose_name': 'Territorio de Hinchadas',
                'verbose_name_plural': 'Territorios de Hinchadas',
            },
        ),
        migrations.CreateModel(
            name='ReferenteHinchas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apodo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('faccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referentes', to='clubes.faccionhinchas')),
            ],
            options={
                'verbose_name': 'Referente de Hinchadas',
                'verbose_name_plural': 'Referentes de Hinchadas',
            },
        ),
        migrations.CreateModel(
            name='AntecedenteClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INCIDENTE', 'Incidente'), ('SANCIÓN', 'Sanción'), ('VIOLENCIA', 'Violencia'), ('DESTRUCCIÓN', 'Destrucción de propiedad'), ('INVASIÓN', 'Invasión de campo'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_incidente', models.DateField()),
                ('lugar', models.CharField(max_length=200)),
                ('sancion_impuesta', models.TextField(blank=True, null=True)),
                ('monto_sancion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='clubes.club')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Antecedente de Club',
                'verbose_name_plural': 'Antecedentes de Clubes',
                'ordering': ['-fecha_incidente'],
            },
        ),
    ]
