# Generated by Django 4.2.7 on 2025-09-21 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('club_local', models.CharField(max_length=100)),
                ('club_visitante', models.CharField(max_length=100)),
                ('estadio', models.CharField(max_length=200)),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='BAJO', max_length=10)),
                ('motivo_alerta', models.TextField(blank=True, null=True)),
                ('relato_hecho', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuentro',
                'verbose_name_plural': 'Encuentros',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('LPF', 'Liga Profesional de Fútbol'), ('ASCENSO', 'Primera Nacional'), ('COPA_ARGENTINA', 'Copa Argentina'), ('COPA_SUDAMERICANA', 'Copa Sudamericana'), ('COPA_LIBERTADORES', 'Copa Libertadores')], max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VIOLENCIA', 'Violencia'), ('DESTRUCCION', 'Destrucción de propiedad'), ('INVASION', 'Invasión de campo'), ('DISPUTA', 'Disputa entre hinchadas'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fecha_incidente', models.DateTimeField()),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.encuentro')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
            },
        ),
        migrations.AddField(
            model_name='encuentro',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.torneo'),
        ),
        migrations.CreateModel(
            name='RankingConflictividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=100)),
                ('cantidad_conflictos', models.IntegerField(default=0)),
                ('nivel_riesgo_promedio', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='BAJO', max_length=10)),
                ('ultimo_incidente', models.DateTimeField(blank=True, null=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.torneo')),
            ],
            options={
                'verbose_name': 'Ranking de Conflictividad',
                'verbose_name_plural': 'Rankings de Conflictividad',
                'ordering': ['-cantidad_conflictos'],
                'unique_together': {('club', 'torneo')},
            },
        ),
    ]
