# Generated by Django 4.2.7 on 2025-09-22 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=250)),
                ('escudo_url', models.URLField(blank=True, null=True)),
                ('estadio', models.CharField(blank=True, max_length=250)),
                ('direccion', models.CharField(blank=True, max_length=500)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DerechoAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, unique=True)),
                ('club', models.CharField(blank=True, max_length=200)),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('fecha_inicio', models.CharField(blank=True, max_length=50)),
                ('fecha_fin', models.CharField(blank=True, max_length=50)),
                ('torneo', models.CharField(blank=True, max_length=50)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Derecho de Admisión',
                'verbose_name_plural': 'Derechos de Admisión',
                'ordering': ['club'],
            },
        ),
        migrations.CreateModel(
            name='OperacionalDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
                ('spreadsheet_id', models.CharField(blank=True, max_length=200)),
                ('torneo', models.CharField(blank=True, max_length=50)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento Operacional',
                'verbose_name_plural': 'Documentos Operacionales',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='encuentro',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='fecha_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='hora_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='last_sync',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='club_local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='club_visitante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='estadio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='last_sync',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='torneo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rankingconflictividad',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rankingconflictividad',
            name='last_sync',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rankingconflictividad',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='encuentro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.encuentro'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
