# Generated by Django 4.2.7 on 2025-09-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_club_derechoadmision_operacionaldoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='escudo_local',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='escudo_visitante',
            field=models.URLField(blank=True, null=True),
        ),
    ]
