# Generated by Django 4.2.7 on 2025-09-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_encuentro_escudo_local_encuentro_escudo_visitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='torneo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
