# Generated by Django 4.2.7 on 2025-09-23 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0004_club_torneo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankingconflictividad',
            options={'verbose_name': 'Ranking de Conflictividad', 'verbose_name_plural': 'Rankings de Conflictividad'},
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_ultima_actividad', models.DateTimeField(default=django.utils.timezone.now)),
                ('activa', models.BooleanField(default=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuarios',
                'ordering': ['-fecha_ultima_actividad'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('VISITA', 'Visita')], default='VISITA', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_actividad', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('puede_ver_relato_hecho', models.BooleanField(default=False)),
                ('puede_editar_datos', models.BooleanField(default=False)),
                ('puede_sincronizar', models.BooleanField(default=False)),
                ('puede_exportar', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('VIEW', 'Visualización'), ('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('SYNC', 'Sincronización'), ('EXPORT', 'Exportación'), ('EDIT', 'Edición')], max_length=20)),
                ('descripcion', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('metodo_http', models.CharField(blank=True, max_length=10, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_accion', models.DateTimeField(default=django.utils.timezone.now)),
                ('exitoso', models.BooleanField(default=True)),
                ('detalles_adicionales', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Acceso',
                'verbose_name_plural': 'Auditorías de Accesos',
                'ordering': ['-fecha_accion'],
                'indexes': [models.Index(fields=['usuario', 'fecha_accion'], name='dashboard_a_usuario_cbb5a2_idx'), models.Index(fields=['tipo_accion', 'fecha_accion'], name='dashboard_a_tipo_ac_04e697_idx'), models.Index(fields=['ip_address', 'fecha_accion'], name='dashboard_a_ip_addr_5e84c6_idx')],
            },
        ),
    ]
