# Generated by Django 4.2.7 on 2025-09-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_rankingconflictividad_options_sesionusuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='barras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='capacidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='fecha_fundacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='ubicacion_sede',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
