# Generated by Django 4.2.7 on 2025-09-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_club_barras_club_capacidad_club_fecha_fundacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='derechoadmision',
            name='apellido',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='derechoadmision',
            name='escudo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='derechoadmision',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
