# Generated by Django 4.2.7 on 2025-09-21 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DerechoAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=100)),
                ('motivo', models.CharField(choices=[('VIOLENCIA', 'Violencia'), ('DESTRUCCION', 'Destrucción de propiedad'), ('INVASION', 'Invasión de campo'), ('DISPUTA', 'Disputa entre hinchadas'), ('COMPORTAMIENTO', 'Mal comportamiento'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_imposicion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('LEVANTADO', 'Levantado'), ('SUSPENDIDO', 'Suspendido')], default='VIGENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Derecho de Admisión',
                'verbose_name_plural': 'Derechos de Admisión',
                'ordering': ['-fecha_imposicion'],
            },
        ),
    ]
