# Generated by Django 4.2.7 on 2025-09-21 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TendenciasKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('frecuencia', models.IntegerField(default=0)),
                ('fecha_tendencia', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tendencia de Keyword',
                'verbose_name_plural': 'Tendencias de Keywords',
                'ordering': ['-frecuencia', '-fecha_tendencia'],
                'unique_together': {('keyword', 'fecha_tendencia')},
            },
        ),
        migrations.CreateModel(
            name='AlertaRedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('fuente', models.CharField(choices=[('TWITTER', 'Twitter'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('TIKTOK', 'TikTok'), ('MEDIO', 'Medio de Comunicación'), ('OTRO', 'Otro')], max_length=20)),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='BAJO', max_length=10)),
                ('keywords', models.JSONField(default=list)),
                ('clubes_mencionados', models.JSONField(default=list)),
                ('fecha_alerta', models.DateTimeField(default=django.utils.timezone.now)),
                ('procesado', models.BooleanField(default=False)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Redes',
                'verbose_name_plural': 'Alertas de Redes',
                'ordering': ['-fecha_alerta'],
            },
        ),
    ]
